services:
  mqtt-broker:
    image: mochimqtt/server
    ports:
      - "1882:1882"
      - "1883:1883"
      - "1880:1880"
    # env_file:
    #   - .env
    volumes:
      - ./mqtt-broker/mqtt-broker-config.template.yaml:/config.yaml
      # - ./mqtt-broker/mqtt-broker.entrypoint.sh:/mqtt-broker.entrypoint.sh
    # entrypoint: ["sh", "/mqtt-broker.entrypoint.sh"]
    restart: unless-stopped

  mongodb:
    image: arm64v8/mongo:4.4.18
    ports:
      - "27017:27017"
    # env_file:
    #   - .env
    volumes:
      - /mnt/sunder/hydroponics/data/mongodb:/data/db
    restart: unless-stopped

  postgres:
    image: arm64v8/postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - /mnt/sunder/hydroponics/data/postgres:/data/postgres
    restart: unless-stopped

  mqtt-to-mongodb-service:
    build:
      context: ../hydroponics-mqtt-to-mongodb-service
    ports:
      - "8080:8080"
    env_file:
      - ../hydroponics-mqtt-to-mongodb-service/.env
    depends_on:
      - mongodb
      - mqtt-broker
    restart: unless-stopped
